### ISSUE TITLE
version and deployment issues

### ISSUE THREAD

**Issue by ntap-johanneswagner** [NetAppDocs/trident#163]
Page: [Deploy with Trident operator](https://docs.netapp.com/us-en/trident/trident-get-started/kubernetes-deploy-operator.html)

Dear Team

we have the following example in the docs:
helm install <release-name> netapp-trident/trident-operator --version 22.1.0 --namespace <trident-namespace>

1. We should be consistent with the version format. even as 22.1.0 is working, everywhere else we are writing it in the format yy.mm.p meaning 22.01.0 would be the consistent writing
2. 22.01 is not the current release, 22.04.0 should be used as most of the people just copy and paste the command
3. I personally would love to have --create-namespace in the example as many people are not only reading from top to bottom but also directly doing everything that's written there. We do not tell upfront that a namespace should be created (even if the people should know how helm works, many of them don't...) and so I experienced it often that people are reading, copy the command, the command fails, helm tells that there needs to be the namespace created, they create the namespace and retry the example again. 
Best Regards
Hannes

**Comment by juliantap** [comment]
@ntap-johanneswagner thank you for your feedback and sorry for the delay. I will work with the team to get this addressed.

**Comment by juliantap** [comment]
Hi @ntap-johanneswagner, because Helm doesn't have proper Semantic versioning we need to use 22.4.0 instead of 22.04.0 for the install instructions. You can see the Helm version on the ArtifactHUB: https://artifacthub.io/packages/helm/netapp-trident/trident-operator

I've updated the current release to 22.4.0.

For the question about `--create-namespace`, as we have that option highlighted in a note below the sample, we won't create a separate example to specify it. 

When the changes merge, this issue will auto-close. However, if you have additional comments, you can continue to comment here. Many thanks for contributing to our Trident documentation!
