### ISSUE TITLE
Title incorrect

### ISSUE THREAD

**Issue by chrismaki** [NetAppDocs/trident#330]
### Page URL

https://docs.netapp.com/us-en/trident/trident-concepts/ontap-drivers.html

### Page title

ONTAP drivers

### Summary

The current title is:

_Astra Control supported drivers_

However I believe it should be:

_Astra Trident supported drivers_

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by chrismaki** [comment]
The first line also has "Control" vs "Trident"

**Comment by juliantap** [comment]
Hi @chrismaki -- this is actually correct. We are intending to show the differentiation between what Asta Trident _provides_ and what Astra Control _supports_. 

However, I agree with you that it's jarring (and confusing) to see Astra Control show up like that out of context. This makes it look like a mistake rather than a clarification. Let me think about how to make this work better. 

Thank you!

**Comment by juliantap** [comment]
Per our conversation, I will close this issue when 23.07 goes live. Thanks, @chrismaki!
