### ISSUE TITLE
Fix PDF links and add doc change links to the Trident doc main page

### ISSUE THREAD

**Issue by crossond** [NetAppDocs/trident#374]
### Page URL

https://docs.netapp.com/us-en/trident/

### Page title

Astra Trident 23.07 documentation

### Summary

On the main first page for Trident docs :   https://docs.netapp.com/us-en/trident/

- The PDF links are not working.
- There are no doc change links on this page.
- Fix PDF links and add doc change links to the Trident doc main page for all versions. 

see attached image

![TridentMainPage_PDF_link_broken_no_doc_change_link](https://github.com/NetAppDocs/trident/assets/52290163/2c3cf926-79d9-4b51-91f1-63b7e9757bb9)

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by juliantap** [comment]
Thanks, @crossond -- the fix for this is in progress!

**Comment by ntap-bmegan** [comment]
@crossond - The menu opacity problem has been corrected and will roll out as sites are regenerated. You can see it already in place in [StorageGRID 11.7](https://docs.netapp.com/us-en/storagegrid-117/). 

I believe that the non-working nature of the links you reported for Trident is related to the opacity problem, as I can download the site PDF for StorageGRID and I can access Trident PDFs from article pages (where there's no opacity problem). 

The doc changes links are available on all article pages, for example https://docs.netapp.com/us-en/trident/trident-rn.html

![image](https://github.com/NetAppDocs/trident/assets/56453501/052d6368-45c2-455a-bddf-424a71cb4d67)

[Learn more](https://docs.netapp.com/us-en/about/docs-netapp-com.html)

@juliantap - Can you republish Trident so that we can confirm the links & opacity?

**Comment by juliantap** [comment]
Pushing a minor change now. I'll verify it works when that completes.

**Comment by ntap-bmegan** [comment]
Thanks, @juliantap.
