### ISSUE TITLE
clarification...

### ISSUE THREAD

**Issue by mdmiller99** [NetAppDocs/trident#397]
### Page URL

https://docs.netapp.com/us-en/trident/trident-managing-k8s/upgrade-operator.html

### Page title

Upgrade a Trident operator installation

### Summary

Step 2 for the helm install states...
helm upgrade <name> trident-operator-23.07.1.tgz

...but step 1 doesn't provide that tgz file.  When you download trident, you get a trident-installer*.tgz file.  Is the operator tgz within that bundle or do you download that elsewhere?

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by mdmiller99** [comment]
I was able to upgrade in one step without first downloading using:  helm upgrade trident netapp-trident/trident-operator --version 23.07.1

Maybe this would be a simpler task for the doc?  Otherwise, please advise on where to find the tgz for the controller.

**Comment by juliantap** [comment]
Thank you, @mdmiller99. I will review this suggestion with dev and get back to you as soon as possible. As we are in the midst of release changes, it will likely be a couple of days. Thank you for your patience :-)

**Comment by juliantap** [comment]
@mdmiller99 

- Yes, `trident-operator-xx.xx.x.tgz` is in `trident-installer.23.10.0.tar.gz/trident-installer/helm/trident-operator-23.10.0.tgz`. 
- Your suggestion is interesting. I will ask whether there is any risk to using `trident upgrade <name> netapp-trident/trident-operator --version xx.xx.x` rather than specifying the `.tgz`. This is the same process as using `trident install` to originally install using Helm.
