### ISSUE TITLE
Enhance documentation for fsType 

### ISSUE THREAD

**Issue by wonderland** [NetAppDocs/trident#75]
Page: [Kubernetes and Trident objects](https://docs.netapp.com/us-en/trident/trident-reference/objects.html)

In section https://docs.netapp.com/us-en/trident/trident-reference/objects.html#kubernetes-attributes

Also based on feedback in this Trident issue: netapp/trident#695

Can we please add `ontap-nas,ontap-nas-economy` to the list of relevant drivers in the table?

Can we please add the following additional explanation below the table?

The `fsType` parameter is used to control the desired file system type for SAN LUNs. In addition, Kubernetes also uses the presence of the `fsType` in a storage class as an indication that a filesystem exists. Volume ownership can only be controlled via the `fsGroup` security context of a pod if `fsType` is set. See https://kubernetes.io/docs/tasks/configure-pod-container/security-context/ for an overview on setting volume ownership via the fsGroup context.
Kubernetes will only apply the `fsGroup` value if

- `fsType` is set in the storage class
- The PVC access mode is `RWO` 

For the `ontap-nas` and `ontap-nas-economy` drivers, a filesystem already exists as part of the NFS export. In order to use `fsGroup` the storage class still needs to specify a `fsType`, though the actual value is irrelevant. You can set it to `nfs`.

**Comment by juliantap** [comment]
@gnarl  & @adkerr do you approve this request?

**Comment by juliantap** [comment]
@balaramesh can you approve this?

**Comment by balaramesh** [comment]
@juliantap yes. Thank you @wonderland for reporting this issue. I think we should add this to the docs. 

1. We should also include ontap-nas-flexgroup to the list of supported drivers
2. One minor change I would recommend is for the last sentence. It should be reworded to "For NFS storage drivers, a filesystem already exists as part of the NFS export. In order to use fsGroup the storage class still needs to specify a fsType. You can set it to `nfs` or any non-null value.:

**Comment by juliantap** [comment]
Thank you, @wonderland! I have combined this change with issue #76. This issue will automatically close when issue #76 merges.
